### ISSUE TITLE
[Mechanics] How are the ball guides going to be fixed in place

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#10]
How are the ball guides going to be fixed in place so they don't move around when in use?

![Fusion360_2022-09-21_19-03-06](https://user-images.githubusercontent.com/32770145/191560272-a3bf7e9d-eeff-4dce-baef-6269a30aef32.png)

**Comment by marcanderetti** [comment]
The sticks will be replaced by M6 bolts

**Comment by Akustav** [comment]
You need 70mm M6 bolts to make them work. I hope you have those, since I dont think we have such bolts in the lab and they seem quite exotic in their usecases.

**Comment by marcanderetti** [comment]
> You need 70mm M6 bolts to make them work. I hope you have those, since I dont think we have such bolts in the lab and they seem quite exotic in their usecases.

I can take bolts from home and cut them to size. not going to be a problem
