### ISSUE TITLE
[Mechanics] Difficult order of assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#11]
Currently the order of assembly for the motor spacer and motor are a little suspect.

First you need to attach the motor, else the sidewalls block the mounting holes:
![image](https://user-images.githubusercontent.com/5435954/192094084-0e660a3d-92de-4d55-915f-e54f6af8f4bb.png)

After that you need you logically should attach the motor-spacer assembly to the sidewall but that is made difficult, because the attachment bolt heads can now interfere with the motor body:
![image](https://user-images.githubusercontent.com/5435954/192094149-0eb71439-d3c2-4eb1-98c4-22e968ff8e80.png)

Is this intentional?

**Comment by marcanderetti** [comment]
made holes in motor mount so the motor screws could be added later.

**Comment by marcanderetti** [comment]
I don't know how many times i have said this, but this is not meant to be adjustable. it just happens to be

**Comment by Akustav** [comment]
Okay, I completely misunderstood it then. Can happen with text chats. Overall the design is quite confusing due to so many bolt holes in the component. You could remove the outer bolt circle entirely and mount the motor using its mounting holes, clamping the spacer between the motor and sidewall (blue holes). Otherwise you can remove around half the outer circle holes because there is no use for them (red crosses). The outer circle bolts still interfere with the motor so you can not remove the spacer without removing the motor completely.

A bolt does not in itself stop the pieces from moving relative to each other. The bolt provides clamping force to create friction between the two components. Shear forces apply in this case so a huge number of bolts is major overkill.

![image](https://user-images.githubusercontent.com/5435954/195391028-b5bdffe1-1733-4857-be28-e5e3f5cb08dc.png)

**Comment by marcanderetti** [comment]
fixed it
