### ISSUE TITLE
[Mechanics] Side swing stick questions

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#12]
I was wondering how do you plan to manufacture those?

They seem to be a complex solution for a simple issue. Would it not be simpler to use a bolt with a blind threaded hole?

![image](https://user-images.githubusercontent.com/5435954/192094381-a295b20e-729c-4260-9384-e85762806ce8.png)

This reduces the count of unique components while providing the same result

**Comment by marcanderetti** [comment]
I was planning to 3d print the stick, and screw from the other side. I thought it would look cooler like this.

**Comment by Akustav** [comment]
What advantage except being cool would that provide? It seems more fragile and uses unique components that when lost/broken are more difficult to replace.

Additionally, how are these pieces fastened? The pieces themselves are 6mm, so what kind of screw will hold them in place?
![image](https://user-images.githubusercontent.com/5435954/193411627-637259be-d1dd-4058-aa5f-e07991ff3177.png)
The same issue is with the other side component that has the fastening hole on the swing arm.

Another thing is the weird sizing of the component stopper sides. One side has a 1mm lip, the other side has 6.4mm
![image](https://user-images.githubusercontent.com/5435954/193411707-b71dff1d-7e96-4e27-a51f-ac83d00b5a4c.png)
I think you mentioned earlier that you had to add a hole to make room for the motors shaft. Why have the piece so long at all?

**Comment by marcanderetti** [comment]
if the 6.4mm piece is so long, it will be held in place by the motor and won't need fastening. The other side will have a bolt and a spacer

**Comment by Akustav** [comment]
Can't we just remove the side swing arms and all components associated with them? The main benefit of these swing arms is smooth motion when adjusting the throwing angle in runtime. This design does not support this approach.

You plan to clamp the internal moving components with the bolt. The two bolts have already fixed spacing with a grey piece. So the bolts can move in the slot and you can clamp the component sandwich without the arms.
![image](https://user-images.githubusercontent.com/5435954/193654307-4db03191-ff04-41e0-b59f-6d26779d63fa.png)

**Comment by Akustav** [comment]
I guess it can add a little support. Still one question remains that how will the ramp pivots fasten to the sidewalls.

Hole 1 is 3mm, hole 2 is 2.5mm. What combination of bolts and other fasteners are used there?

![image](https://user-images.githubusercontent.com/5435954/195392976-18c840e2-3170-4d37-b9e2-25ff85621e30.png)

**Comment by marcanderetti** [comment]
made both 2.5mm inside, so a screw can be added later. Also changed the direction of the swing stick, so a screw could be added from the outside
![image](https://user-images.githubusercontent.com/59764874/196791895-8827ab84-b527-40cd-ab63-60165cc0470e.png)
