### ISSUE TITLE
[Mechanics] Upper guide stick and spacer question

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#13]
Was wondering out of what you plan to do the spacer and stick?
![image](https://user-images.githubusercontent.com/5435954/192094473-43bb9e78-4f81-4b9b-a32d-f06ad6ed034d.png)

Would it not be simpler to use a 10mm female-female spacer and 2 flat screws?

**Comment by marcanderetti** [comment]
doesn't really matter, I was planning on 3d printing and press-fitting the stick. The model currently does not allow tolerance for screws

**Comment by Akustav** [comment]
I do not think 3D-printing is a appropriate solution. It is not a catch-all answer. It should be attempted to avoid bespoke components that are ultra-specific. Maybe there is a better solution like using a F-F spacer fastened with recessed screw.

**Comment by marcanderetti** [comment]
well then i can use a threaded rod and nuts. Really anything works that fits in between. It's not like it's going to mass production

**Comment by Akustav** [comment]
In most cases it is good to use off-the-shelf components because they are easy to acquire and replace. It is good practice cause it reduces development time. Making one custom component is easy but when you need to 20 of said components, taking them off a shelf is better use of time and effort.

Anyways... Press-fitting 3D-printed sticks may break or take a lot of time to properly fit because tolerances for them are not that great. The stick may also be different in diameter across its length.

Threaded rods + nuts may interfere with the sliding action when you plan to fix it on both sides

**Comment by marcanderetti** [comment]
i was meaning to cut a threaded rod to be the length of the stick. But anyways, by our availability of components, 3d printing a 5-minute print 4 times is still going to be faster than going to the hardware store. also, these thing don't have to be press-fitted THAT hard 😄

**Comment by Akustav** [comment]
Compared to a hardware store it may be a good solution yeah but we should have a collection of spacers and these would be instantly available. I would also suggest using countersunk screws instead of normal socket cap head screws. It looks sleeker and does not interfere with any other moving parts.

**Comment by marcanderetti** [comment]
Well i can look into it while manufacturing

**Comment by Akustav** [comment]
It is possible to resolve before "looking into it while manufacturing". I suggest using 10 mm female-female spacers with M3 countersinks. This fixes everything in place rigidly.

**Comment by marcanderetti** [comment]
Changed everything to adapt a 10mm spacer

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/196791064-f454853a-6874-4c7a-aec0-d19109772d69.png)
