### ISSUE TITLE
[Mechanics] excessive play in angle adjustment

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#16]
Currently the swing arms connect to the moving part of the ramp using a slot. Why is that? There seems  to be a lot of play there as well and the swing arms to not fix the ramp in place:

![image](https://user-images.githubusercontent.com/5435954/193412287-1e9d3220-ff24-48c5-b834-c3efadf27616.png)

**Comment by marcanderetti** [comment]
Obviously, it's meant to be adjustable. The whole assembly will be held together by the M6 bolts and friction.

**Comment by Akustav** [comment]
This may be obvious for you but not obvious on first look.
