### ISSUE TITLE
[Mechanics] Thrower may bend when throwing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#18]
With a big hole in  the side of the main wall the thrower motor has a easy time bending when throwing. The hole does not seem to have a practical use so it could be filled to better support the motor.

![image](https://user-images.githubusercontent.com/5435954/193657162-1385d083-0f1c-4118-aa36-4422c9607cb3.png)

**Comment by Akustav** [comment]
A additional way to add rigidity is to add a 45 mm spacer close to the motor that collect the two side walls. If you place the spacer in front of the motor it also protects the motor from potential physical damage from other robots and ramming in general.

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/193664345-e303f859-7967-4977-9db5-fe7a83c1f0f1.png)

Used a simpler method, added long 3mm bolts to prevent flexing and provide protection. Also removed the holes from walls

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/193674171-91c86f59-f828-45b1-9541-baaf616aaa53.png)
Raised mount sides to meet the top plate, for even more structural integrity.
