### ISSUE TITLE
[Mechanics] thrower can be hard to clamp when whole robot is assembled

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#19]
Currently it is very difficult to fasten and release the the bolts because other parts of the chassis can be in the way.
To me it seems that it should be easily adjustable but when it can only be tweaked when removed from the robot removes flexibility that the design is supposed to add. Technically I think it is possible to place the thrower and other components in a manner that there is minimal interference but it requires some thought in the design.

![image](https://user-images.githubusercontent.com/5435954/193661437-706d437d-0935-43ed-9e53-9f06066959e3.png)

Maybe you can use a universal joint driver but you use so large screws that the sockets for fastening will be large. Additionally you would need to hold both sides to tighten/release the bolts.

It is quite difficult to fix the access problem but the both side issue can be resolved by milling a pocket for the bolt heads that act as wrench. The pocket could be 2 or so mm deep.

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/193669502-55b599c0-1b35-4d51-b7b1-1d810edd1203.png)


Looks like it easily fits a 10mm flat wrench
