### ISSUE TITLE
[Mechanics] Dogbones missing from sidewalls

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#2]
Assuming the sidewalls are going to be milled out, dogbones for sharp corners are missing.
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_inside_sharp_corners

![pilt](https://user-images.githubusercontent.com/32770145/191555958-fadc2e65-1341-425b-8c91-a056d0887875.png)

**Comment by Akustav** [comment]
The current radius is 0.75mm. Is this intended? What sized mill do you plan to use? 
![image](https://user-images.githubusercontent.com/5435954/192093543-7d3bf3a1-d612-484e-b006-1726179f6625.png)

**Comment by marcanderetti** [comment]
I messed up the radius and diameter, will change it.

**Comment by marcanderetti** [comment]
made new dogbones
