### ISSUE TITLE
[Mechanics] tab holes larger than tabs

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#20]
Currently the holes for mounting tabs of the thrower are large and don't locate the thrower. Is this intended?
![image](https://user-images.githubusercontent.com/5435954/193662469-2d5befd5-50b0-4dc5-8dbb-b06474c39f10.png)

**Comment by marcanderetti** [comment]
This was changed because I had different sized tab holes on my model. Will change back to original.

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/193671356-c5151997-2567-4ee8-b45a-3b7894038537.png)
