### ISSUE TITLE
[Mechanics] No path for motor cables

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#21]
There is currently no hole in the sidewall for the motor power cables. With the current mounting hole locations, one of these areas can be used:

![image](https://user-images.githubusercontent.com/5435954/195396405-f39cf22f-af06-4314-bbb6-05686e85dfd2.png)

This can be changed by rotating the motor mounting holes.

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/196193641-3afe7533-2cec-4f73-aeb3-b74753990b44.png)
Power cables will run like this
