### ISSUE TITLE
[Mechanics] Edit existing sketches and features to make changes

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#22]
Creating new sketches and features should be avoided if existing ones can be changed. Sketches should be properly dimensioned and constrained to make doing changes easier.

![motor_mount_r_many_sketches](https://user-images.githubusercontent.com/1595938/195404503-de72bb15-49f3-4a24-bcbf-dae0578bb2b2.gif)

**Comment by Akustav** [comment]
In the future I think we can prevent such cases. Closing it for now.
