### ISSUE TITLE
MCU pin assignement

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#25]
![image](https://user-images.githubusercontent.com/1595938/198868156-25bce403-7d0a-47ca-ba29-259e41c91b88.png)

Did you use STM32CubeIDE for creating the pin assignment?
Based on the schematic I could not find pin assignment that would work.

For example timer 2 is already used for encoder and PA5 pin does not have any other timer channels available for PWM output:
![image](https://user-images.githubusercontent.com/1595938/198868375-db351158-8416-41d0-9050-feedb5cfa287.png)

Some more information on how to configure timers in STM32CubeIDE is on the firmware page:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/firmware.html

**Comment by raimo0** [comment]
Fixed added servo pwm signal.
