### ISSUE TITLE
Clearance between tracks is very small

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#28]
![image](https://user-images.githubusercontent.com/1595938/198869588-78d7201a-84be-4880-bc0f-35dda89a5a97.png)

Signals on tracks will couple to adjacent tracks and cause noise. Typical recommendation is to keep tracks at least 3H apart, where H is distance between signal and reference layer. H for JLCPCB JLC3313 stackup is 0.1mm, so there should be at least 0.3 mm clearance between the tracks. If there is not enough room, then less clearance might be fine, but running traces in parallel should be minimised.

Tracks on the picture can be made narrower (0.2mm or 0.15mm) to create more space between them.

**Comment by raimo0** [comment]
Made the tracks thinner and added more space between them.
