### ISSUE TITLE
Via minimum annular ring size

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#29]
![image](https://user-images.githubusercontent.com/1595938/198870237-f50408ab-6859-4344-913c-3aff821fa0fd.png)

0.3/0.5 mm vias have annular ring size (0.1mm) that is under the minimum recommended size.

JLCPCB recommendation is 0.13mm. Smallest recommended via size is 0.2/0.45 mm (annular ring 0.125mm).
https://jlcpcb.com/capabilities/Capabilities

It's better to use 0.2/0.45 mm vias.

**Comment by raimo0** [comment]
Fixed
