### ISSUE TITLE
[Mechanics] Not clear where thrower motor cables run

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#3]
From the current model it is unclear from where motor power cables run. Would be great if they can be found on the model, at least a representation of the cable exit area is needed.
Verify the location on your actual motor.

![Fusion360_2022-09-21_18-22-06](https://user-images.githubusercontent.com/32770145/191556260-409e5c33-22bf-43f2-8324-1b5e5708fcdf.png)

**Comment by marcanderetti** [comment]
motor cables can turn in a 90 degree angle and won't get in the way. Alse we're not quite sure yet where to run the cables

**Comment by Akustav** [comment]
I guess the whole motor attachment can be rotated to adjust the cable exit location. Overall I would suggest to run the cable from this area so it does not interfere with the ball or other elements of the thrower.

![image](https://user-images.githubusercontent.com/5435954/192093732-29429833-30bb-4dc1-9390-d3ccead556a1.png)
