### ISSUE TITLE
Make high current connections wider

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#30]
![image](https://user-images.githubusercontent.com/1595938/198875349-a4ea52f6-507e-4a59-ac51-8a0a673ded97.png)

Current copper widths might work fine, but since there is room, it would make since to make copper polygons wider to help with current carrying and cooling capabilities.

1.63 mm conductor can carry about 5.4 A of current at 20 degree temperature rise:
![image](https://user-images.githubusercontent.com/1595938/198875566-799c5819-597d-44e2-965d-8b0cc4559485.png)

Also if the currents share the same path then components on that path will see more noise from other components on that path. It's better to have separate (straight) path for each component.

Something like this would be much better:
![image](https://user-images.githubusercontent.com/1595938/198875785-b4c51759-65c1-4b08-9adc-64d67712f025.png)

On MCU side the entire half of the bottom layer could be 3.3V polygon.
![image](https://user-images.githubusercontent.com/1595938/198875950-49779a78-4d58-4a2c-aab5-78e3262c27de.png)
![image](https://user-images.githubusercontent.com/1595938/198875985-bd2b4b4a-ecea-463a-b8cc-47d7c1cf500a.png)

**Comment by raimo0** [comment]
Made the connections wider.
