### ISSUE TITLE
Route USB data signals as differential pair

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#32]
![image](https://user-images.githubusercontent.com/1595938/198876135-175d312d-00e4-4562-8562-bf4f45f7b35a.png)

USB data signals are 90 ohm differential pair and should be routed as such.
Tracks should be kept straight and symmetrical as possible to minimise impedance changes.
Correct impedance is achieved by varying width and spacing of the tracks.

JLCPCB has impedance calculator:
https://cart.jlcpcb.com/impedanceCalculation
![image](https://user-images.githubusercontent.com/1595938/198876351-f890393a-7396-4a47-8ec4-18e4400748c5.png)

According to the calculator, when using spacing of 8 mil (about 0.2 mm) the tracks have to be 6.03 mil (about 0.15 mm).

With Altium Designer's default settings, the differential pair net names have to end with (`_P` and `_N`):
![image](https://user-images.githubusercontent.com/1595938/198876583-02e20ef1-78f7-460d-bb81-f1eb228245d6.png)

On the schematic a differential pair directive and blanket over both pins should be added:
![image](https://user-images.githubusercontent.com/1595938/198876555-1658b390-86f2-416a-b169-7776141ee9d1.png)
![image](https://user-images.githubusercontent.com/1595938/198876598-b5bb31b6-2a2b-44ae-a638-f309a19dfe54.png)

On properties panel of Differential Pair directive a Diff. Pair Net Class should be added:
![image](https://user-images.githubusercontent.com/1595938/198876640-8ccd3a10-73dd-4adb-8e99-67544c1ab7cd.png)
![image](https://user-images.githubusercontent.com/1595938/198876692-5d4f6a6e-6b84-4ac5-af1e-3195003aa640.png)

In PcbDoc file, do Design -> Import:
![image](https://user-images.githubusercontent.com/1595938/198876751-861266de-4809-44aa-af29-5ed91fff2db2.png)

Edit or create new Differential Pair Routing Rule:
![image](https://user-images.githubusercontent.com/1595938/198876842-1f391a4e-052e-48b2-9698-bee79fd5d891.png)

Change component placement to allow differential tracks to be straight as possible:
![image](https://user-images.githubusercontent.com/1595938/198877621-edc54e86-c0dc-44ea-b984-207516661419.png)

Use Interactive Differential Pair Routing (Shift + Ctrl + W)
![image](https://user-images.githubusercontent.com/1595938/198877522-41ef16ab-17c7-4f8c-880d-87cd7728526a.png)

If stubs are created during routing, adjust the tracks manually to get rid of them. Stubs create reflections in signals.
![image](https://user-images.githubusercontent.com/1595938/198877772-d760a889-1379-4e63-bf05-5ed08f736fa5.png)

Resulting diff pair tracks should be straight as possible with plenty of clearance between the pair and other tracks:
![image](https://user-images.githubusercontent.com/1595938/198877822-b082aa9c-1a79-4939-b417-72e940b8e2d4.png)

**Comment by raimo0** [comment]
Routed the USB data as a differential pair.
