### ISSUE TITLE
Programmer connector clearance

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#34]
Programmer connector is quite wide and won't fit with current encoder connector placement.

![image](https://user-images.githubusercontent.com/1595938/198878377-569800fc-f65d-4bcf-86f9-90cd6705018b.png)

More info:
* https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/review_summary.html#_make_sure_there_is_enough_room_for_micromatch_and_programmer_connectors
* https://github.com/ut-robotics/picr21-team-shaq/issues/52

**Comment by raimo0** [comment]
Moved the connector
