### ISSUE TITLE
Add more capacitance to switching regulator output

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#35]
![image](https://user-images.githubusercontent.com/1595938/200124083-a2dcdabd-4e27-497d-b2f8-2eddee5713a6.png)

100 nF is probably too little.

Texas Instruments Webench recommends 47 uF:
![image](https://user-images.githubusercontent.com/1595938/200124208-47c6a4b3-5450-4784-8dc1-9e3d2e0759be.png)
https://webench.ti.com/power-designer/switching-regulator?powerSupply=0

**Comment by raimo0** [comment]
Fixed.
