### ISSUE TITLE
Ball sensor

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#36]
![image](https://user-images.githubusercontent.com/1595938/200124612-4f740988-4419-4561-8b8a-154b4a153de3.png)

Is the servo used for angle adjustment or ball holding?

For holding a ball sensor should be added. Otherwise it's hard to know when the servo should be stopped.

In the lab we have IS471FE sensors and 3mm IR LEDs.

**Comment by raimo0** [comment]
The servo was for angle adjustment but I added a second servo for ball holding and a connector for the IR sensor.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/200167768-aff16edc-496c-483d-bac8-098df7bf4e2e.png)
![image](https://user-images.githubusercontent.com/1595938/200167868-7e097fa3-e603-474e-a384-89ca156da28c.png)

PA4 pin is not 5V tolerant.
From [datasheet](https://www.st.com/resource/en/datasheet/stm32g441kb.pdf):
![image](https://user-images.githubusercontent.com/1595938/200167799-820936fe-0732-431a-b46e-b3d8ca1b840a.png)
![image](https://user-images.githubusercontent.com/1595938/200167849-99813483-50f6-48bf-8eb5-273e9403f043.png)

Also `SERVO_PWN` should probably be `SERVO_PWM`:
![image](https://user-images.githubusercontent.com/1595938/200167913-75e58de1-d206-4b3a-b6c7-b529f2ba0163.png)

**Comment by raimo0** [comment]
Changed the IR sensor pin to PF0 and fixed the typos.
