### ISSUE TITLE
Optimise switching regulator layout

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#38]
Connection to inductor can be made wider by moving the passible components.
![image](https://user-images.githubusercontent.com/1595938/200126820-50947364-b2a6-40df-b3c4-a4a6aaaec037.png)

Usually it's recommended to place smaller/lower capacitance capacitors closer to power inputs:
![image](https://user-images.githubusercontent.com/1595938/200127055-0a855185-8b37-4d1b-89e4-c9f029c45a9b.png)

**Comment by raimo0** [comment]
Optimised the layout.
