### ISSUE TITLE
Mounting screw clearance

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#39]
Typical M3 screw head has diameter of 5.5 mm. One of the connectors is too close to the mounting hole:
![image](https://user-images.githubusercontent.com/1595938/200173082-39cb9771-4533-4f0e-a973-cc6669a1ab49.png)

**Comment by raimo0** [comment]
![image](https://user-images.githubusercontent.com/112662827/200174861-d86ecd41-115b-44b4-9e38-853441ede0dc.png)
Fixed.
