### ISSUE TITLE
[Mechanics] Text in sidewalls might not manufacturable

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#4]
Assuming the walls are going to be milled, I think we don't have a small enough end mill to cut out the text in the walls.

**Comment by marcanderetti** [comment]
removed the text

**Comment by Akustav** [comment]
As a note, I have engravement tips for milling. They are conical 45,  60 and 90 degree mills. These can be used to mill text into components. They look something like this:

![image](https://user-images.githubusercontent.com/5435954/192093801-5f2d0205-8109-4d92-906d-cd2a08516a45.png)
