### ISSUE TITLE
Create Gerber X2 files

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#40]
Create Gerber X2 layer and drill files and commit them to repository for ordering the manufacturing.

![image](https://user-images.githubusercontent.com/1595938/200173289-e6bad47c-a0d8-4022-bff0-f817549e5e73.png)
![image](https://user-images.githubusercontent.com/1595938/200173297-85702c01-84b6-44df-a5cb-36c6920d00db.png)

**Comment by raimo0** [comment]
Added the files.
