### ISSUE TITLE
[Mechanics] suggest not using plastic parts for wheel - motor fastening

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#41]
Team mu had a issue with their omniwheels where they used plastic and threaded inserts to fasten the wheel to the shaft of the motor. They also experienced failures to that area. I therefore suggest using the lathe to cut out a aluminum wheel fastener.

![image](https://user-images.githubusercontent.com/5435954/202236367-8f986800-3ff7-4477-9bfb-48a0f6859b12.png)

**Comment by marcanderetti** [comment]
Will use an aluminium hub
![image](https://user-images.githubusercontent.com/59764874/202896177-4f976931-e784-472b-ab00-2fbacf7090d1.png)
