### ISSUE TITLE
[Mechanics] holes in wheel covers very large

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#43]
The holes on top of the wheel covers are currently very large, at 5.6mm. Is this intentional? How will it be fastened

![image](https://user-images.githubusercontent.com/5435954/202237306-bf813077-13af-4b3c-a265-7b1293d02a71.png)

**Comment by marcanderetti** [comment]
made them smaller, for the different type of bolt
![image](https://user-images.githubusercontent.com/59764874/202896152-9bcbfd86-49ff-4c31-beda-bc07551beb7a.png)
