### ISSUE TITLE
[Mechanics] had to assemble top plate

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#45]
If you want to have back support for the motors you should make the fit for these tabs loose to reduce the headache of assembly. The more tight fitting components there are, the harder the robot is to assemble.

![image](https://user-images.githubusercontent.com/5435954/202239518-f454e520-1e3c-4dee-b672-be690c5a584e.png)

**Comment by marcanderetti** [comment]
Made motor mount ends diagonal so the assembly would be easier
![image](https://user-images.githubusercontent.com/59764874/202897159-cd15911d-15c9-4046-9faf-3ce74a9bd0df.png)
![image](https://user-images.githubusercontent.com/59764874/202897168-93fcd42b-ed67-470f-81c4-f89d6b1cc04b.png)

**Comment by Akustav** [comment]
Overall I would suggest having room on both X and Y axis

**Comment by marcanderetti** [comment]
I will manualli sand down the edges after manufacturing
