### ISSUE TITLE
[Mechanics] no camera on the model

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#46]
There is currently no camera.
Additionally I suggest to fix the camera in place so it can not move. This reduces the danger of the camera moving and screwing with the adjustments done in code. A field of view cone will help you a lot

![image](https://user-images.githubusercontent.com/5435954/202240212-5165b874-a05c-470a-b7ff-65d9347d2bc0.png)

**Comment by marcanderetti** [comment]
Fixed these issues
![image](https://user-images.githubusercontent.com/59764874/203113259-6ebbaf45-f98d-4030-95c8-0710ef8a50e3.png)
![image](https://user-images.githubusercontent.com/59764874/203114106-c0d58683-e218-411a-8ab6-203a979a5af1.png)

**Comment by Akustav** [comment]
There is currently no room for the cameras USB cable:

![image](https://user-images.githubusercontent.com/5435954/204857168-fc0c8113-4cdc-4cbb-b2e9-1701c3b38d5a.png)

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/205132356-8186c24f-2f8b-4464-94bb-d1cd90b90110.png)
fixed it
