### ISSUE TITLE
[Mechanics] no batteries mounted

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#47]
It is currently hard to see if a battery actually fits into the box inside the chassis.

![image](https://user-images.githubusercontent.com/5435954/202240760-a7f86206-f288-4f0b-a2df-f4986b1c3c94.png)

**Comment by marcanderetti** [comment]
The holder is bigger than the batteries, so that batteries would fit regardless of them being expanded or not

**Comment by marcanderetti** [comment]
mounted a battery
![Uploading image.png…]()
