### ISSUE TITLE
[Mechanics] Motor spacer add mounting holes on other side

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#5]
Since the motor is going to be attached to the motor spacer, the forces when a ball is thrown will get carried to the swing stick and the bolts at the front.
Adding mounting holes to the other side can add more rigidity.

![Fusion360_2022-09-21_18-33-33](https://user-images.githubusercontent.com/32770145/191557526-fa3b57ee-6391-47fd-8cf6-248a7b52eac1.png)

**Comment by marcanderetti** [comment]
made more mounting holes. all might not be usable due to interference with the swing

**Comment by marcanderetti** [comment]
changed bolt mounting direction from motor mount -> spacer to spacer -> motor mount. Now all 8 bolts fit perfectly
