### ISSUE TITLE
[Mechanics] a bump in the roller slots

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#51]
There is a bump in the roller slots. What is it for? If it is to support the roller, i suggest putting the supports as close to the shaft as possible. It might be hard to do so I suggest using a round slot for the shafts so it is simpler to add a lip in a way that it does not interfere with the rollers moving parts.

![image](https://user-images.githubusercontent.com/5435954/202244504-5665106c-11e5-47e1-aee4-82d536e2d338.png)

**Comment by marcanderetti** [comment]
Made smaller and moved closer
![image](https://user-images.githubusercontent.com/59764874/202894346-5bb837b3-f169-4adc-9a87-b59d773e6dd1.png)
