### ISSUE TITLE
[Mechanics] no power plug or switches

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#52]
There are currently no places for a power plug or switches on the chassis

**Comment by marcanderetti** [comment]
Made holes for switches, power connectors etc
![image](https://user-images.githubusercontent.com/59764874/203112949-2eb74b3a-32a8-4f26-951c-76d177626c6e.png)

**Comment by Akustav** [comment]
Current holes would not make it possible to mount switches, for example. I suggest consulting with some guidelines from here:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_pc_power_adapter_socket

**Comment by marcanderetti** [comment]
Made adjustments 
![image](https://user-images.githubusercontent.com/59764874/205128925-1d149c1d-d00f-4221-9e4e-7933e1fb00fd.png)
![image](https://user-images.githubusercontent.com/59764874/205129004-bbe477c0-f736-42a3-a628-4bde48a13524.png)

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/205318384-4b01d5c6-7759-4d6c-8ccb-288ae5ad6c50.png)
