### ISSUE TITLE
[Mechanics] nothing stopping thower internal ramp from bending outward

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#54]
The current design has no elements topping the internal ramps from bending under pressure from the ball.

![image](https://user-images.githubusercontent.com/5435954/202246647-4284db02-f34f-4cee-af83-8497dfe5c696.png)

**Comment by marcanderetti** [comment]
Will use 20mm F-F spacer
![image](https://user-images.githubusercontent.com/59764874/203020830-d6469cb7-f050-4335-a9fc-ef998dfe48c8.png)
