### ISSUE TITLE
[Mechanics] thrower can currently not be mounted

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#55]
The tabs are too wide:

![image](https://user-images.githubusercontent.com/5435954/202246863-ba6eb2dc-d7d7-4cbb-a7fd-fe0c433c5214.png)

**Comment by marcanderetti** [comment]
Cleared this issue
![image](https://user-images.githubusercontent.com/59764874/202894197-e7edfa34-bc56-41ac-b093-ddaff6d88834.png)
