### ISSUE TITLE
RGB and robot axis misaligned

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#58]
Currently these are misaligned. Is it intended?

![image](https://user-images.githubusercontent.com/5435954/204858502-a06adf80-37c0-4b4a-b6e6-0a0ba767da65.png)

**Comment by marcanderetti** [comment]
Centered it
![image](https://user-images.githubusercontent.com/59764874/205132306-faad63a5-506c-4de7-9c14-652788eb78de.png)
