### ISSUE TITLE
Chassis blocking view at front of robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#59]
Currently the top plate blocks your view of balls at  the front of the robot:

![image](https://user-images.githubusercontent.com/5435954/204858698-e3847141-f323-4576-a2cd-074c99fa592e.png)

**Comment by marcanderetti** [comment]
made camera view a lot better
![image](https://user-images.githubusercontent.com/59764874/205110647-1aeaf0f3-4436-439b-884c-fdb2fabeed05.png)
