### ISSUE TITLE
[Mechanics] Motor spacer holes wont support available bolts

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#6]
The current holes for the bolt heads in the motor spacer have a diameter of 5 mm.
Heads of the bolts we have are 5,5 mm in diameter.

![Fusion360_2022-09-21_18-41-31](https://user-images.githubusercontent.com/32770145/191558263-25dbd6e4-2234-4eea-958d-467690878ffc.png)

Screw heads are also taller than 2 mm.

Dimensions:
![image](https://user-images.githubusercontent.com/1595938/191559598-069a3b13-aa8d-454d-80e5-35cdf592dfbf.png)
https://www.tme.eu/Document/569d510bbd6921a3db18021de3c420e1/B3x10_BN11.pdf

**Comment by marcanderetti** [comment]
made the holes 5.55mm x 3.1mm.
