### ISSUE TITLE
Is this a hole for a spacer?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#61]
Is this hole meant to be for a spacer? Does it actually fit there? The spacer is a good idea but does not seem to currently fit.

![image](https://user-images.githubusercontent.com/5435954/204860723-6b84cbf2-c763-4518-977b-ab7eda3ae1c3.png)

**Comment by marcanderetti** [comment]
added the spacer, moved the hole a little
![image](https://user-images.githubusercontent.com/59764874/205128274-c2824a1e-1440-405e-bda1-bdb59262ac5d.png)
