### ISSUE TITLE
Ball floating between roller and thrower motor

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#62]
Currently the ball is not fed into the thrower by the roller:

![image](https://user-images.githubusercontent.com/5435954/204861127-fabd8af2-fd7e-4186-b0d4-b04105a9e3b3.png)

I suggest something like a double-internal ramp where the roller has its own little curve that feeds the ball into the thrower without release of too much pressure. Something like this:

![image](https://user-images.githubusercontent.com/5435954/204861385-503d863b-968c-4016-aaaf-601fadaaa88f.png)

**Comment by marcanderetti** [comment]
Modified the ramp. Thank you!
![image](https://user-images.githubusercontent.com/59764874/205095771-ffdaea86-fa73-4216-91a1-c3d711f8c54d.png)
