### ISSUE TITLE
Almost zero clearance on robot thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#63]
There is almost no clearance on the robot. It might get stuck on the carpet and will have a very hard time moving sideways due to its parts dragging on the carpet. Additionally there is no room for any screws to mount the extra centering rails.

![image](https://user-images.githubusercontent.com/5435954/204861803-992138be-d859-44c9-8596-1c15c62d0431.png)

I suggest not having the additional rails or have them around 5mm off the ground.

**Comment by marcanderetti** [comment]
Made some clearance changes
![image](https://user-images.githubusercontent.com/59764874/205096230-7d0ebe52-fe78-4dda-a6f8-21718d56d999.png)
