### ISSUE TITLE
No sensor to detect where ball is in the thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#64]
There currently is no way to detect how much a ball has been grabbed. This can lead to the situation where you unintentionally throw it when wanting to hold it. I suggest adding a IR sensor to around here that signals the mainboard that a ball is well located in the thrower.

![image](https://user-images.githubusercontent.com/5435954/204862275-1dd510be-3123-43dd-9911-8f1e9e30ec90.png)

**Comment by marcanderetti** [comment]
made holes for IR sensor
![image](https://user-images.githubusercontent.com/59764874/205136108-9bee1f76-1729-4526-b058-52a8939c4f98.png)
![image](https://user-images.githubusercontent.com/59764874/205136430-a146f39c-1f22-45e7-9b3a-1a7b71da4a9a.png)
![image](https://user-images.githubusercontent.com/59764874/205136455-76acaa8f-308d-4015-ad4d-eba333d4a281.png)

**Comment by Akustav** [comment]
This sensor position should work yeah but what holds the sensor and LED in place? I suggest a little plate that pushes the sensor into its socket and is fastened with 1-2 screws:

![image](https://user-images.githubusercontent.com/5435954/205441670-2ba16b36-f126-406c-ab8c-6a72dd57ffec.png)

**Comment by marcanderetti** [comment]
Made a bracket to hold the LED and the sensor. The paint shows how the prongs will be routed
Sensor side:
![image](https://user-images.githubusercontent.com/59764874/205446693-ecb71c16-e4ac-4afb-ae30-0150b6c495bb.png)
LED side:
![image](https://user-images.githubusercontent.com/59764874/205446662-fce5683e-62c2-4e56-a415-f5778a209c81.png)
