### ISSUE TITLE
No electronics attached to the robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#66]
You should have a place for the mainboard and step-up converter inside the chassis.

**Comment by marcanderetti** [comment]
![image](https://user-images.githubusercontent.com/59764874/205133747-cce306d3-d015-4cf6-b3fb-d45834053f59.png)
![image](https://user-images.githubusercontent.com/59764874/205133799-9805d551-0c93-4f22-82dd-0632c9be285b.png)

**Comment by Akustav** [comment]
You will most likely not be able to fit the SUB in the mainboard without some additional cutouts:

![image](https://user-images.githubusercontent.com/5435954/205441555-cb7baa0f-427a-4477-9301-c04df6d3ac38.png)

**Comment by marcanderetti** [comment]
Made a bigger hole in the camera holder, so cables could be routed
![image](https://user-images.githubusercontent.com/59764874/205446308-3840d01e-8074-4e89-a702-349d0df6e217.png)
![image](https://user-images.githubusercontent.com/59764874/205446324-52a2a15f-1ea8-49d3-a49c-138a9fc0944f.png)
