### ISSUE TITLE
No room for screw that holds extended ramp to robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#68]
There seems to be no room for a normal screw here:

![image](https://user-images.githubusercontent.com/5435954/205442096-524b593b-47b8-4331-a7c3-6762f0db5ac2.png)

**Comment by Akustav** [comment]
I also suggest to use countersunk screws here as well:
![image](https://user-images.githubusercontent.com/5435954/205442127-8295d8d0-24b7-452f-880e-d334e7a30b36.png)

**Comment by marcanderetti** [comment]
I will be using countershrunk screws in places like these
![image](https://user-images.githubusercontent.com/59764874/205445996-c6073895-1569-4393-a701-21fea4144e91.png)

**Comment by marcanderetti** [comment]
Also made the front a bit thicker, for added strength
![image](https://user-images.githubusercontent.com/59764874/205447518-236dfef4-3d71-4432-8696-935e4e0e9e88.png)

**Comment by Akustav** [comment]
The component is 3D printed so you should model the chamfers there as well. Drilling them afterward can compromise the 3D printed component.

**Comment by marcanderetti** [comment]
added chamfter on the parts
![image](https://user-images.githubusercontent.com/59764874/205487554-eac62ae4-f126-4f5b-b7bf-fcf8962cad83.png)
![image](https://user-images.githubusercontent.com/59764874/205487559-66f1670f-79ab-4c8d-962f-e12e843deffd.png)
![image](https://user-images.githubusercontent.com/59764874/205487580-fd874bf1-081e-4827-9b19-79e462fca33b.png)
