### ISSUE TITLE
Thrower motor cable hole goes nowhere

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#69]
The hole leads nowhere currently:

![image](https://user-images.githubusercontent.com/5435954/205442175-b206655f-a749-4c66-a782-2d05f5509af4.png)

**Comment by marcanderetti** [comment]
I deemed it too much to sketch, so i just shortened the cable
![image](https://user-images.githubusercontent.com/59764874/205445912-6aed0070-6ddf-41e7-981d-f44df6ffeba1.png)

**Comment by Akustav** [comment]
I think you missed the point. Where does the cable run? The hole is above the top plate so the cable cant go into the chassis.

![image](https://user-images.githubusercontent.com/5435954/205456391-d8b003b5-15bf-4e78-ac5b-3eae04dc9333.png)

**Comment by marcanderetti** [comment]
Oh right... I completely missed that little detail 🤣 
Made a little hole thingy for the cable
![image](https://user-images.githubusercontent.com/59764874/205487448-be6f548e-cce2-4c62-a66d-63162e99d681.png)
