### ISSUE TITLE
[Mechanics] Motor-side swing stick might have interference with motor shaft

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-gibibot#7]
Since the send of the motor-side swing stick is very close to the thrower motor's shaft, there might be interference, because the shaft sticks out quite a bit.
In the current model, the distance between these parts is 0,6 mm, which might not be enough.

![Fusion360_2022-09-21_18-44-25](https://user-images.githubusercontent.com/32770145/191558850-510403c5-0636-489f-9e59-1f2009b73e36.png)

![pilt](https://user-images.githubusercontent.com/32770145/191559430-6bf8e489-69fc-4304-a3c7-76a53cf1076d.png)

**Comment by marcanderetti** [comment]
the 3mm hole should have been enough, but i made a 4mm x 1mm hole just in case. This is an easy thing to manually fix later.
