### ISSUE TITLE
Do you plan to fasten the servo horn to the servo?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#70]
There should be a screw that fixes the horn to the servo. Do you plan to use it or is there another solution?

![image](https://user-images.githubusercontent.com/5435954/205442262-00598beb-59a5-406e-8e89-9a0e9a32c5a1.png)

**Comment by marcanderetti** [comment]
Yes, there is a screw. I didn't see a point in modelling that, since it doesn't change anything
