### ISSUE TITLE
Servo clipping into chassis

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-gibibot#71]
The back servo currently clips into the top plane:

![image](https://user-images.githubusercontent.com/5435954/205442326-1d858694-3e42-4269-85bf-b0dc65236920.png)

**Comment by marcanderetti** [comment]
Made a cutout for the servo
![image](https://user-images.githubusercontent.com/59764874/205487282-cf02223c-d391-44e4-9db5-b2c32eb3c15f.png)
