### ISSUE TITLE
[Mechanics] Thrower motor spacer holes are not properly aligned

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-gibibot#9]
![image](https://user-images.githubusercontent.com/1595938/191556841-4925e7ff-ce37-4817-99ef-d53930823fe2.png)

Sketches aren't fully defined.
![image](https://user-images.githubusercontent.com/1595938/191557063-70add97f-d444-401c-8061-ac83a5d2f963.png)
![image](https://user-images.githubusercontent.com/1595938/191557612-87a5030f-40bf-4bda-bb1e-36eafe5d4786.png)
![image](https://user-images.githubusercontent.com/1595938/191557123-b3b50114-279f-4896-ae1a-d1ee9ed02b35.png)

It's probably better to use circular pattern for these holes instead of having multiple sketch lines and dimensions.

**Comment by marcanderetti** [comment]
made new holes using a circular pattern. everything should be fine now.
